# outlook properties
outlook:
  imap:
    server: outlook.office365.com
    port: 993
  mail-box:
    username: kthangav@jcp.com
    password: 
    folder: Inbox/noreply
    subject: 'Splunk Alert:P1_JMSExceptions'
    from: NoReply@len-sh01.jcpenney.com
    alert_time_period_in_minutes: 240
    mail_scan_time: 1800000

#email properties
email:
  smtp:
    server: mail.jcpenney.com
    port: 25
  subject: Jaana | Email Subject
  to_recipients: kthangav@jcp.com, pmurugan@jcp.com
  cc_recipients:
  sender: eComm-SRE-Automation@jcp.com
  template:
    file-path-name: 
    mime-type: html
  attachments:
    - 'temp/test.xls'

#Excel File Parser
excel-parser:
    read:
      file-path-name: 'temp/test.xls'
      sheet: 'test sheet'
    write:
      file-path-name: 'temp/test.xls'
      sheet: 'test sheet'



#CSV File Parsing Properties
csv-parser:
  input-file: test.csv
  delimiter: ','
  skip-initial-space: True
  include-quotes: False
  fields-to-read:
      - field_name_1
      - field_name_2

# XML File parsing properties
xml-parser:
  input-file: test.xml
  elements-to-read:
      clearancePrice:
        - element : element1    
        - element : element2
